# Generated by Django 4.1.5 on 2023-04-24 16:45

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('package_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dest_x', models.IntegerField()),
                ('dest_y', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('status', model_utils.fields.StatusField(choices=[('ready', 'ready'), ('delivering', 'delivering'), ('delivered', 'delivered')], default='ready', max_length=100, no_check_for_status=True)),
            ],
            options={
                'db_table': 'delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('upsaccount', models.CharField(max_length=100)),
                ('dest_x', models.IntegerField()),
                ('dest_y', models.IntegerField()),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='package',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='truck_id',
        ),
        migrations.AlterModelOptions(
            name='truck',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
