# Generated by Django 4.1.5 on 2023-04-29 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ups', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('whid', models.IntegerField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
            options={
                'db_table': 'warehouse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryProof',
            fields=[
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ups.delivery')),
                ('proof', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('deliveries', models.ManyToManyField(blank=True, to='ups.delivery')),
                ('trucks', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ups.truck')),
            ],
        ),
    ]
