# Generated by Django 4.2 on 2023-04-29 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ORDER',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_addr_x', models.IntegerField()),
                ('order_addr_y', models.IntegerField()),
                ('time', models.TimeField()),
                ('upsid', models.CharField(max_length=10, null=True)),
                ('price', models.FloatField(max_length=1000)),
            ],
            options={
                'db_table': 'ORDER',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_desc', models.CharField(max_length=100, null=True, unique=True)),
                ('price', models.FloatField(max_length=100)),
                ('catalog', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addrX', models.CharField(max_length=10, null=True)),
                ('addrY', models.CharField(max_length=10, null=True)),
                ('upsid', models.CharField(max_length=10, null=True)),
                ('userName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_desc', models.CharField(max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('wh_id', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('OPEN', 'open'), ('PACKING', 'packing'), ('PACKED', 'packed'), ('LOADING', 'loading'), ('LOADED', 'loaded'), ('DELIVERING', 'delivering'), ('DELIVERED', 'delivered')], default='open', max_length=50)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amazon.order')),
                ('package_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon.userprofile')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amazon.product')),
            ],
            options={
                'db_table': 'package',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon.userprofile'),
        ),
    ]
