
CREATE TABLE PRODUCT (
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100),
    PRODUCT_DESC VARCHAR(100) NULL UNIQUE,
    PRICE DECIMAL(10,2),
    CATALOG VARCHAR(100)
);

CREATE TABLE "ORDER" (
    ORDER_ID SERIAL PRIMARY KEY,
    ORDER_ADDR_X INT,
    ORDER_ADDR_Y INT,
    TIME TIME,
    ORDER_OWNER_ID INTEGER NULL,
    UPS_ID INT,
    PRICE DECIMAL(10,2),
    FOREIGN KEY (ORDER_OWNER_ID) REFERENCES AMAZON_USERPROFILE (ID) ON DELETE CASCADE
);

CREATE TABLE PACKAGE (
    PACKAGE_ID SERIAL PRIMARY KEY,
    PACKAGE_DESC VARCHAR(100) NULL,
    PACKAGE_OWNER_ID INTEGER NULL,
    AMOUNT INT,
    PRODUCT_ID INT NULL,
    WH_ID INT NULL,
    ORDER_ID INT NULL,
    STATUS VARCHAR(50) DEFAULT 'packing',
    FOREIGN KEY (PACKAGE_OWNER_ID) REFERENCES AMAZON_USERPROFILE (ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID) ON DELETE SET NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES "ORDER" (ORDER_ID) ON DELETE SET NULL
);
