version: '2'
services:
  db:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=20230101
        - POSTGRES_USER=postgres
        - POSTGRES_DB=mini_ups
      restart: always
      volumes:
            - data-volume:/var/lib/postgresql/data
  web-server:
    build: ./back-server-python
    volumes:
      - ./back-server-python:/code
    depends_on:
      - db
  web-init:
    build: .
    volumes:
      - .:/frontcode
    links:
      - db:db
    depends_on:
      - db
volumes:
   data-volume:
