# Generated by Django 4.1.5 on 2023-04-15 20:44

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_x', models.IntegerField()),
                ('dest_y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('available', 'available'), ('pickingup', 'pickingup'), ('delivering', 'delivering')], default='available', max_length=100, no_check_for_status=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('pickedup', 'pickedup'), ('delivering', 'delivering'), ('delivered', 'delivered')], default='pickedup', max_length=100, no_check_for_status=True)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ups.package')),
                ('truck_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ups.truck')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='truck_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ups.truck'),
        ),
    ]
