# Generated by Django 4.1.5 on 2023-04-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0002_delivery_order_remove_shipment_package_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='truck',
            table='truck',
        ),
    ]
